# git-cliff configuration
# https://git-cliff.org/docs/configuration

[changelog]
header = """# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n
"""
body = """
{%- macro remote_url() -%}
  https://github.com/torrentclaw/unarr
{%- endmacro -%}

{% if version -%}
  ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{%- else -%}
  ## [Unreleased]
{%- endif %}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
{% for commit in commits
| filter(attribute="scope")
| sort(attribute="scope") %}
  - **{{ commit.scope }}**: {{ commit.message }}
    {%- if commit.breaking %} (**BREAKING**){% endif %}
{%- endfor -%}
{% for commit in commits %}
  {%- if not commit.scope %}
  - {{ commit.message }}
    {%- if commit.breaking %} (**BREAKING**){% endif %}
  {%- endif %}
{%- endfor %}
{% endfor %}
"""
footer = """
{%- macro remote_url() -%}
  https://github.com/torrentclaw/unarr
{%- endmacro -%}

{% for release in releases -%}
  {% if release.version -%}
    {% if release.previous.version -%}
      [{{ release.version | trim_start_matches(pat="v") }}]: {{ self::remote_url() }}/compare/{{ release.previous.version }}...{{ release.version }}
    {% else -%}
      [{{ release.version | trim_start_matches(pat="v") }}]: {{ self::remote_url() }}/releases/tag/{{ release.version }}
    {% endif -%}
  {% else -%}
    {% if release.previous.version -%}
      [Unreleased]: {{ self::remote_url() }}/compare/{{ release.previous.version }}...HEAD
    {% endif -%}
  {% endif -%}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_parsers = [
  { message = "^feat", group = "Added" },
  { message = "^fix", group = "Fixed" },
  { message = "^perf", group = "Performance" },
  { message = "^refactor", group = "Changed" },
  { message = "^style", group = "Changed" },
  { message = "^doc", group = "Documentation" },
  { message = "^ci", group = "CI/CD" },
  { message = "^chore\\(deps\\)", skip = true },
  { message = "^chore", group = "Other" },
  { message = "^test", skip = true },
]
protect_breaking_commits = false
filter_commits = false
tag_pattern = "v[0-9].*"
sort_commits = "newest"
